# Generated by Django 5.1.6 on 2025-04-17 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='ledger.recipe'),
        ),
    ]
